iter20
Xacor/go-metrics pull request #22
Opened 2023-10-14 09:24 UTC by Xacor

2023-10-16 21:57 UTC, valentinsoe requested changes
Спасибо за работу!

Но в текущей версии не подключатся анализаторы SA*.
Касательно же самой проверки на наличие os.Exit - мне кажется в алгоритме есть ошибка, лучший способ меня опровергнуть, написать еще тест:)

2023-10-16 21:57 UTC, valentinsoe commented on cmd/agent/main.go
> +	Version string = "N/A"
Названия переменных не соответсвуют заданию.
С одной стороны мелочь. С другой - если у вас система сборки расчитывает на конкретные названия переменных, то работать не будет:)

2023-10-16 21:57 UTC, valentinsoe commented on tools/exitchecker/exitchecker.go
> +			return true
Кажется если в AST после main окажется любая другая функция с os.Exit() - то проверка все равно скажет что в функции main ошибка.

2023-10-16 21:57 UTC, valentinsoe commented on tools/staticlint/staticlint.go
> +	for _, v := range staticcheck.Analyzers {
Таким образом мы не добавим SA* анализаторы. У них же конкрентые имена в v.Analyzer.Name, а не wildcard как в мапе staticChecks

2023-10-17 06:34 UTC, Xacor commented on tools/exitchecker/exitchecker.go
> +			return true
Действительно была ошибка. Поправил, добавил тест.

2023-10-17 06:35 UTC, Xacor commented on tools/staticlint/staticlint.go
> +	for _, v := range staticcheck.Analyzers {
Поправил, переделал на регулярки.

2023-10-17 22:22 UTC, valentinsoe approved these changes
Спасибо за исправления!
Работу принимаю

2023-10-18 06:31 UTC, merged

2023-10-20 13:20 UTC, Xacor commented
Пришлось отправить повторно, так как практикум не засчитал прошлое ревью и не дает доступ к следующей главе. В поддержке не помогли, и сказали отправить повторно.